name: smoove (lumpy) genotype
description: smoove simplifies and speeds calling and genotyping SVs for short reads; genotype tool
input:
  - cohort sv vcf.gz
output:
  - single sample genotyped vcf.gz
notes: |
  * We implement the population calling approach, see related tools aswell.
  * This wrapper relies on the xcat-specific module system (otherwise change environment.yaml)
authors:
  - Fabian Brand