name: pindel
description: pindel - Pindel can detect breakpoints of large deletions, medium sized insertions, inversions, tandem duplications and other structural variants at single-based resolution from next-gen sequence data.
authors:
  - Sugi Sivalingam
input:
  - BAM file
output:
  - deletion
  - short insertion
  - inversion
  - tandem duplication
  - large insertion
  - unassigned breakpoints
