name: ngs-cli download
description: Wrapper for getting input files from a variety of sources.
authors:
  - Fabian Brand
input:
  - any file
output:
  - target file on local drive
notes: |
  * Downloads the given input file from any remote location.
  * Requires the sample parameter to find the correct file.