project: covid_wgs_bonn
sample-sheet: samples.tsv
files-table: files.tsv
ref:
  # GRCh37
  genome: /home/brand/scratch/library/human_g1k_v37_decoy.fasta
  refseq: /gpfs01/daten/cuba/Resources/Genomes/Human/GATK/b37/all_refseq_exons_ip_12.bed
  1kg-variants: /home/brand/scratch/library/1000G_phase3_v4_20130502_chr22.sites.vcf.gz
  # GRCh38
  # genome: /ceph01/scratch/brand/library_hg38/Homo_sapiens_assembly38.fasta
  # refseq: /home/brand/scratch/library_hg38/all_refseq_exons.bed
  # 1kg-variants: /ceph01/scratch/brand/library_hg38/ALL.chr22.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
  known-variants: 
    - '/home/brand/scratch/library/Mills_and_1000G_gold_standard.indels.b37.vcf'
    - '/home/brand/scratch/library/1000G_phase1.indels.b37.vcf'
