name: samtools stats
description: Wrapper for the various samtools stats commands
input:
  - bam file
  - bai file
output:
  - stats file
  - flagstats file
  - idxstats file
notes: |
  * Generates the flagstat output if `flagstat` is in output
  * Generates the idxstats output if `idxstat` is in output
  * Throws if `stats` is not a key in the output
authors:
  - Fabian Brand