name: smoove (lumpy) merge
description: smoove simplifies and speeds calling and genotyping SVs for short reads; merge tool
input:
  - single call vcf gz files
output:
  - merged sv vcf.gz
notes: |
  * We implement the population calling approach, see related tools aswell.
  * This wrapper relies on the xcat-specific module system (otherwise change environment.yaml)
authors:
  - Fabian Brand