name: smoove (lumpy) call
description: smoove simplifies and speeds calling and genotyping SVs for short reads; call tool
input:
  - bam file
output:
  - sv vcf.gz file
notes: |
  * We implement the population calling approach, see related tools aswell.
  * This wrapper relies on the xcat-specific module system (otherwise change environment.yaml)
authors:
  - Fabian Brand