name: picard MarkDuplicates
description: Wrapper for picards MarkDuplicates.
authors:
  - Fabian Brand
input:
  - bam file
  - bai file
output:
  - duplicate marked bam file
  - duplicate marking metrics